language: go
sudo: false

go:
    - 1.7

before_install:
  - go get github.com/stretchr/testify/require
  - go get github.com/stretchr/testify/assert

script:
  - go get -v -t . ./_examples
  - go test ./_examples
  